title: "Zhargal Bubeev | Data Center & AI"
description: "Portfolio of Zhargal Bubeev, AI & Data Center Technician"
author: "Zhargal Bubeev"

url: "https://untrauhan.github.io"

remote_theme: pages-themes/hacker@v0.2.0
paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme  # ✅ Добавляем поддержку remote_theme!

collections:
  pages:
    output: true
    permalink: /:path/
