
title: "Zhargal Bubeev | Data Center & AI"
description: "Portfolio of Zhargal Bubeev, AI & Data Center Technician"
author: "Zhargal Bubeev"
baseurl: ""
url: "https://UntraUhan.github.io"

theme: minima
paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
