title: "Zhargal Bubeev | Data Center & AI"
description: "Portfolio of Zhargal Bubeev, AI & Data Center Technician"
author: "Zhargal Bubeev"
baseurl: ""
url: "https://untrauhan.github.io"

remote_theme: jekyll-theme-hacker
paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

collections:
  pages:
    output: true
    permalink: /:path/
