title: "Zhargal Bubeev | Data Center & AI"
description: "Portfolio of Zhargal Bubeev, AI & Data Center Technician"
author: "Zhargal Bubeev"
baseurl: ""
url: "https://untrauhan.github.io"

# Используем поддерживаемую тему GitHub Pages
remote_theme: pages-themes/cayman@v0.2.0

paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

collections:
  pages:
    output: true
    permalink: /:path/
"""