name: Jekyll CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Сборка Jekyll-сайта
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v2

      - name: Установка Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Установка Jekyll и зависимостей
        run: |
          gem install jekyll bundler
          bundle install

      - name: Сборка Jekyll-сайта
        run: bundle exec jekyll build --strict_front_matter

  link-check:
    name: Проверка ссылок
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v2

      - name: Запуск проверки ссылок
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --timeout 20s
